### ISSUE TITLE
Administrator panel

### ISSUE THREAD

**Issue by diphieee** [BaldMenStudios/BuildTickets#4]
An Admin panel, to monitor progress efficiently by every player.

**Main Menu admin panel**
![image](https://github.com/Zffu/BuildTickets/assets/87574941/f9ffb7ab-5295-47fa-842b-14a20f4081e4)

Just so you don't need to open all the panels by other commands.

**Panel 1**
- Filter by Builder
- See how many tickets handled
- filter by time: 1h ago, 12h ago, 1d ago, 15d ago, 30d ago...
![image](https://github.com/Zffu/BuildTickets/assets/87574941/e31a3798-1407-49ba-8b02-9e9de7df29de)
When you hover over the player, it shows the stats.

**Panel 2**
- Delete Tickets
- Edit Tickets
- Create Tickets
![image](https://github.com/Zffu/BuildTickets/assets/87574941/68c358e8-c11b-445f-a398-85ab4ca791ae)
shows which tickets there are, if you left click it edits, right click is delete. (ADD MAKE SURE THAT YOU WANT TO DELETE?)

**Panel 3**
Permissions maybe?
Admins can give permissions to players using the panel?

**Comment by Zffu** [comment]
only last panel is missing. Will be in future update

**Comment by Zffu** [comment]
Panel 3 will not be implemented as it will not be very useful as LuckPerms and stuff exists.
